### ISSUE TITLE
Exception 'You do not have permission to view this repository' on scheduled workflow run

### ISSUE THREAD

**Issue by spier** [github/issue-metrics#166] opened 2023-11-01 22:44 UTC
I have a workflow that runs on a monthly schedule to generate PR and Issue metrics.

When it ran on the schedule yesterday, it [failed](https://github.com/InnerSourceCommons/InnerSourcePatterns/actions/runs/6714828057/attempts/1) with this error:
> You do not have permission to view this repository; Check you API Token.

However when re-running the workflow again, it [succeeded](https://github.com/InnerSourceCommons/InnerSourcePatterns/actions/runs/6714828057).

Not sure if this was a blips in the matrix or what happened here :)

## For context: 

The workflow file is in the same repo for which metrics are generated. 
Therefore I believe I can use the default `secrets.GITHUB_TOKEN` token that is automatically generated for each workflow run.
Also the fact that the 2nd run succeeded seems to indicate that this is not a general permission issue.

**Comment by zkoppert** [comment] 2023-11-03 03:18
Oh wow! That is surprising. My guess is that this is a glitch but will keep the issue open for now in case we get any other reports of the same thing.

**Comment by zkoppert** [comment] 2023-12-02 01:19
Closing as we've not seen this again. Please re-open if spotted again.

**Comment by EricStG** [comment] 2024-04-08 21:03
We have the same issue. In a schedule, we get:
```
Starting issue-metrics search...
Searching for issues...
You do not have permission to view this repository; Check you API Token.
```
But run it manually and every thing is fine

**Comment by zkoppert** [comment] 2024-04-09 02:41
@EricStG can you confirm that the PAT you are using manually and in the action are the same?

Is your workflow referring to the default token or one in your repository secrets?

**Comment by EricStG** [comment] 2024-04-09 12:34
@zkoppert We're using the default token, it's the same regardless on how we trigger the job

**Comment by zkoppert** [comment] 2024-04-10 22:10
@EricStG I'd recommend setting up a Personal Access Token or App private key and ID. The default token in my understanding is unable to be granted cross repo permissions. Here are some docs with your options for setting those up: 
- See Step 5 listed here: https://github.com/github/issue-metrics?tab=readme-ov-file#use-as-a-github-action
- GitHub App authentication method: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/about-authentication-with-a-github-app
- GitHub Personal Access Token Method: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic

**Comment by zkoppert** [comment] 2024-04-10 22:24
Interesting. Maybe I'm pulling on the wrong thread. Do you grant permissions in your workflow file?

**Comment by EricStG** [comment] 2024-04-10 22:26
Yes, we grant `issues: write` and `pull-requests: read`

Here's the workflow
```yaml
name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: "repo:${{ github.repository }} is:pr is:merged closed:${{ env.last_month }} -author:app/renovate"
          HIDE_LABEL_METRICS: true
          HIDE_TIME_TO_ANSWER: true
```

**Comment by zkoppert** [comment] 2024-04-11 04:38
Can you print the value of github.repository and ensure the format and repo its pointing to are correct? org/reponame ie.  github-linguist/linguist

**Comment by EricStG** [comment] 2024-04-11 12:00
they are both the same, `repo:owner/repo`
from the logs, the arguments passed to the action are identical in every way

**Comment by zkoppert** [comment] 2024-04-11 23:59
Interesting. @jmeridth Any thoughts on this one? Something I'm missing?

**Comment by jmeridth** [comment] 2024-04-12 15:45
@zkoppert like you, this sounds like a token issue to me but it working on second attempt is the weird issue.  I'm going to test out some stuff to see if I can recreate the problem.  Thank you @spier @EricStG for reporting this.  We are looking into it.

**Comment by EricStG** [comment] 2024-04-12 18:23
@jmeridth just to make sure:
- The schedule workflow never works
- Running the same workflow manually always works
- Retrying the failed scheduled workflow also works 🤷‍♂️

**Comment by lawang24** [comment] 2024-04-26 04:38
can confirm had the same issue as above

**Comment by lawang24** [comment] 2024-04-29 15:45
This issue seems to mirror symptoms of former issue #189 and thus might also be solved by feature request #217

One potential explanation for the mysterious behavior of failing on scheduled runs but succeeding on subsequent manual reruns could be other GHAs also hitting the search API at the same time? If a repo  wants to track other metrics too and has several different Github Actions using this API running at at the same schedule (ex: first hour of month), they could be stack up and cause rate limit of API. However, by the time the repo administrator sees this failure and manually reruns it, the rate limit has already expired.

Unsure how to replicate this easily or how to fix it, but with some suggestions would be open to giving it a go

**Comment by zkoppert** [comment] 2024-04-30 23:40
Yes, whether directly related to the cause or not, fixing rate limiting will at least rule out a potential cause. That seems like the best first place to tackle here.

**Comment by spier** [comment] 2024-05-01 07:51
Let me just cheerlead a bit from the sidelines 👏 

I am super happy that my initial bug report has taken on this life of its own and other cases of seemingly related issues were added. Also the responsiveness of the maintainers has been amazing. Thank you all for chiming in and exploring how this could be fixed/improved.

Lastly, the point by @lawang24 about multiple GHAs that run in parallel exceeding the GHA Search API rate limits does seem like a possible explanation indeed.

Again, thank you all for making open source awesome ❤️

**Comment by jmeridth** [comment] 2024-05-18 23:09
@spier @EricStG could you please retreat with latest. Think we solved this one. Thank you.

**Comment by EricStG** [comment] 2024-05-28 18:56
@jmeridth Sorry haven't had the time to cycle back on this, but it's going to self-test over the weekend 😅
I'll report back when it does

**Comment by EricStG** [comment] 2024-06-06 15:17
@jmeridth It worked, thanks so much!

**Closed** 2024-06-06 16:35 UTC

**Comment by sbland** [comment] 2024-07-10 11:23
I hit this issue today. Is there a specific number of issues that will cause this? I tried to pull all issues instead of last month.
